### ISSUE TITLE
Special attributes not passing some parameters to scoped function

### ISSUE THREAD

**Issue by Rob-pw** [somajs/somajs#11]
http://plnkr.co/edit/j6h2zohwzGGbw6iaXwRt?p=preview

Demonstrated above, expected functionality is differing from actual. 

Only scoped variables and inline-primitives are passed to function.

**Comment by soundstep** [comment]
@Rob-pw 

These are not issues. This happens because there is no syntax parser in soma template. This is for example different than angularJS that contains a syntax parser that changes string to javascript.

The only thing that can be passed are object from the scope, and path to these objects.

A few exceptions could be added, for example for the boolean, but I'm not sure I would ever add a parser (mainly for size).

**Comment by Rob-pw** [comment]
That's understood, albeit a tad unfortunate. Such functionality would allow passing server-formed objects through to function calls, such as:

For example, C# MVC (using Razor syntax)
```c#
<button data-click="changeLanguage({id: @language.id, name: @language.name});">@language.name</button>
```

I agree that adding a syntax parser is overkill, just to support this functionality. Might it also aid in support minor view logic such as ```<div data-show="{{someArray.length > 2}}"></div>```?
